// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtGuDkjHXL-0M1TnsmxrNF6XLqcbewgQY',
    appId: '1:927264643140:web:ddd56cbb910a0104f4c411',
    messagingSenderId: '927264643140',
    projectId: 'health-and-wellness-39c4f',
    authDomain: 'health-and-wellness-39c4f.firebaseapp.com',
    storageBucket: 'health-and-wellness-39c4f.firebasestorage.app',
    measurementId: 'G-ZX27Z9GYF8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAR1BOZeGbzXAs8diQhL3Wm6nnIBF17-cQ',
    appId: '1:927264643140:android:7a74d4cd95dceb6ff4c411',
    messagingSenderId: '927264643140',
    projectId: 'health-and-wellness-39c4f',
    storageBucket: 'health-and-wellness-39c4f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByC-Sd9CLGMEDI2M_NeZDGnFIOsOHFhNE',
    appId: '1:927264643140:ios:1b2b184debf58939f4c411',
    messagingSenderId: '927264643140',
    projectId: 'health-and-wellness-39c4f',
    storageBucket: 'health-and-wellness-39c4f.firebasestorage.app',
    iosBundleId: 'com.example.healthandwellness',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByC-Sd9CLGMEDI2M_NeZDGnFIOsOHFhNE',
    appId: '1:927264643140:ios:1b2b184debf58939f4c411',
    messagingSenderId: '927264643140',
    projectId: 'health-and-wellness-39c4f',
    storageBucket: 'health-and-wellness-39c4f.firebasestorage.app',
    iosBundleId: 'com.example.healthandwellness',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtGuDkjHXL-0M1TnsmxrNF6XLqcbewgQY',
    appId: '1:927264643140:web:32ee9a4e52153dfff4c411',
    messagingSenderId: '927264643140',
    projectId: 'health-and-wellness-39c4f',
    authDomain: 'health-and-wellness-39c4f.firebaseapp.com',
    storageBucket: 'health-and-wellness-39c4f.firebasestorage.app',
    measurementId: 'G-QZXF8B4QCN',
  );
}
